### ISSUE TITLE
Release v1.10.0

### ISSUE THREAD

**Issue by mempirate** [chainbound/fiber-ts#5]
```[tasklist]
- [x] Update `fiber-proto` (`git submodule update --remote fiber-proto`)
- [x] Regenerate and implement the new gRPC bindings (build.sh)
- [x] Implement only the non-deprecated streams
- [x] Use `ethereumjs` for transaction types (always return signer too! recovering it takes too long in JS)
- [x] Use https://github.com/ChainSafe/lodestar to decode SSZ beacon blocks
- [x] For execution payloads, convert to `ethereumjs` blocks
- [x] For transactions and beacon blocks, have a "raw" variant that just returns the RLP / SSZ encoding
- [x] Add `x-client-version` header to all gRPC streams
```

**Comment by thedevbirb** [comment]
I need to look at it further but I have already spent half a day on it and I've found the following:
- fiber-ts is a CommonJS project
- lodestar is an ESModule project
- grpc-tools outputs JavaScript for CommonJS [reference](https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools#usage)


There is a good amount of incompatibility between the two module systems.

Integrating an ESModule in a CommonJS project is very difficult because you need to use dynamic `import()` which returns a `Promise`. 
Making this project an ESModule and integrating CommonJS files should be "easier" (still haven't made it work properly, but close) but this would be probably a breaking change.

The Bun runtime helps with this, but not all people have started using it yet.
